blueprints/auth.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session
from exts import mail, db
from flask_mail import Message
from flask import request
import string
import random
from models import EmailCaptchaModel, UserModel
from .forms import RegisterForm, LoginForm, ForgotPasswordForm
from werkzeug.security import generate_password_hash, check_password_hash


# /auth
bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    elif "username" in request.form:
        form = LoginForm(request.form)
        if form.validate():
            username = form.username.data
            password = form.password.data
            user = UserModel.query.filter_by(username=username).first()
            if not user:
                print("User does not exist in the DB server！")
                return redirect(url_for("auth.login"))
            if check_password_hash(user.password, password):
                session['user_id'] = user.id
                return redirect(url_for("gpt.chat"))  # redirect("/code")

            else:
                print("Wrong Password！")
                return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.login"))
    elif "username_register" in request.form:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username_register.data
            password = form.password_register.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return f"Fail Registration {form.errors}"  # redirect(url_for("auth.login"))
    elif "username_forgot" in request.form:
        form = ForgotPasswordForm(request.form)
        if form.validate():
            email = form.email_forgot.data
            username = form.username_forgot.data
            password = form.password_forgot.data
            user = UserModel.query.filter_by(email=email).first()
            user.username = username
            user.password = generate_password_hash(password)
            db.session.commit()
            return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return f"Fail Resetting Password {form.errors}"  # redirect(url_for("auth.login"))


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")


@bp.route("/captcha/email")
def get_email_captcha():
    email = request.args.get("email")

    source = string.digits
    cap = []
    for i in range(0, 4):
        cap = cap + random.sample(source, 1)
    captcha_string = "".join(cap)
    message = Message(subject="Registration Captcha", recipients=[email], body=f"Your Verification Code is：{captcha_string}")
    mail.send(message)
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha_string)
    db.session.add(email_captcha)
    db.session.commit()
    # RESTful API
    # {code: 200/400/500, message: "", data: {}}
    return jsonify({"code": 200, "message": "", "data": None})

blueprints/gpt.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session, g, escape
from exts import db
from flask import request
from models import UserModel, HistoryModel
from decorators import login_required
import openai

bp = Blueprint("gpt", __name__, url_prefix="/gpt")

openai.api_key = ""


@bp.route("/chat")
@login_required
def chat():
    history = HistoryModel.query.filter_by(user_id=g.user.id).order_by(HistoryModel.create_time.desc())
    return render_template("chat.html", history=history)


@bp.route("/workspace")
@login_required
def workspace():
    history = HistoryModel.query.filter_by(user_id=g.user.id).order_by(HistoryModel.create_time.desc())
    query = HistoryModel.query.filter_by(user_id=g.user.id).order_by(HistoryModel.create_time.desc()).first()
    user_input = query.content
    gpt_output = openai.Completion.create(
        model="text-davinci-003",
        prompt=generate_prompt(user_input),
        temperature=0.6,
        max_tokens=2000
    )
    result = gpt_output.choices[0].text
    # result = "FAKE RESPONSE: this appears when gpt is not ready"

    response = escape("This is answer: \n" + result)
    print(generate_prompt(user_input))
    return render_template("workspace.html", user_input=user_input, response=response, history=history)


def generate_prompt(programming_topic):
    return """Generate a code example related to {}.

Topic: {}
Code:""".format(
        programming_topic,
        programming_topic.capitalize()
    )

blueprints/index.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session, g
from exts import mail, db
from flask import request


bp = Blueprint("index", __name__, url_prefix="/")


@bp.route("/")
def intro():
    return render_template("intro.html")

blueprints/qa.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session
from .forms import QuestionForm
from models import QuestionModel, AnswerModel
from exts import db
from flask import request


bp = Blueprint("qa", __name__, url_prefix="/qa")


@bp.route("/blogs")
def blogs():
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
    return render_template("Q&A.html", questions=questions)


@bp.route("/detail/<qa_id>")
def detail(qa_id):
    question = QuestionModel.query.get(qa_id)
    return render_template("target-page.html", question=question)


@bp.route("/search")
def search():
    q = request.args.get("q")
    questions = QuestionModel.query.filter(QuestionModel.title.contains(q)).all()
    return render_template("Q&A.html", questions=questions)

templates/Q&A.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags for character set and responsive design -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question and Answer</title>

    <!-- Link to the external stylesheet for styling -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Q&A.css') }}">

    <!-- Favicon for the browser tab -->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

    <!-- Include Font Awesome kit for icons -->
    <script src="https://kit.fontawesome.com/442f5b06e6.js" crossorigin="anonymous"></script>
</head>
<body>
<!-- Header Section -->
<header>
    <nav class="top-menu">
        <ul>
            <!-- Navigation links -->
            <li><a href="{{ url_for("gpt.chat") }}">CodeGPT</a></li>
            <li><a href="{{ url_for("index.intro") }}">Introduction</a></li>
            {% if user %}
                <li><a href="{{ url_for("index.intro") }}">{{ user.username }}</a></li>
            {% else %}
                <li><a href="{{ url_for("auth.login") }}">Sign In/ up</a></li>
            {% endif %}
            <li><a class="active" href="{{ url_for("qa.blogs") }}">Q&A</a></li>
            <li style="float:right"><a href="#"> Ask a Question</a></li>
        </ul>
    </nav>
</header>

<!-- Title and Search Section -->
<div class="Q_A">Question and Answer</div>
<div class="search-container">
    <form method="GET" action="{{ url_for('qa.search') }}" >
        <!-- Input field for search query -->
        <input type="text" id="search" name="q" placeholder="Search...">

        <!-- Submit button for search -->
        <button type="submit" class="search-button">
            <i class="fa-solid fa-magnifying-glass" style="color: #ffffff;"></i>
        </button>
    </form>
</div>

<!-- Question Filter Dropdown Section -->
<div class="question_select">
    <div class="select_btn">
        <!-- Dropdown button for question filter -->
        <span class="text_btn">Question Filter</span>
        <span class="arrow_down">
                <i class="fa-sharp fa-solid fa-chevron-up" style="color: #ffffff;"></i>
            </span>
    </div>
    <ul class="list">
        <!-- List items for question filter options -->
        <li class="list_items">
            <!-- Checkbox icon -->
            <span class="checkbox">
                    <i class="fa-solid fa-check check_icon" style="color: #ffffff;"></i>
                </span>
            <!-- Filter option text -->
            <span class="item_text">All Questions</span>
        </li>
        <li class="list_items">
                <span class="checkbox">
                    <i class="fa-solid fa-check check_icon" style="color: #ffffff;"></i>
                </span>
            <span class="item_text">Answers</span>
        </li>
        <li class="list_items">
                <span class="checkbox">
                    <i class="fa-solid fa-check check_icon" style="color: #ffffff;"></i>
                </span>
            <span class="item_text">No Answers</span>
        </li>
    </ul>
</div>

<!-- Question Container Section -->
<div class="question_container">
    <ul class="question-ul" id="questionList">
        {% for question in questions %}
            <div class="question_box {% if question.answers %}has_answers{% endif %}">
                <h2><a href="{{ url_for('qa.detail', qa_id=question.id) }}">{{ question.title }}</a></h2>
                <!-- Question description -->
                <p>{{ question.content }}</p>
            </div>
        {% endfor %}
    </ul>
</div>

<!-- JavaScript Section -->
<script>
    const select_btn = document.querySelector(".select_btn");
    const list_items = document.querySelectorAll(".list_items");
    const text_btn = document.querySelector(".text_btn");

    select_btn.addEventListener("click", () => {
        select_btn.classList.toggle("close");
    });

    list_items.forEach(list_item => {
        list_item.addEventListener("click", () => {
            list_items.forEach(item => {
                if (item !== list_item) {
                    item.classList.remove("checked");
                }
            });

            // Toggle selection state
            list_item.classList.toggle("checked");

            // Update the displayed filter option
            const optionName = list_item.textContent.trim();
            text_btn.textContent = optionName;

            const hasAnswers = list_item.textContent.trim() === "Answers";
            const noAnswers = list_item.textContent.trim() === "No Answers";

            document.querySelectorAll(".question_box").forEach(questionBox => {
                questionBox.style.display = "block"; // 默认显示所有问题

                if (hasAnswers && !questionBox.classList.contains("has_answers")) {
                    questionBox.style.display = "none"; // 隐藏没有答案的问题
                }

                if (noAnswers && questionBox.classList.contains("has_answers")) {
                    questionBox.style.display = "none"; // 隐藏有答案的问题
                }
            });
        });
    });
</script>
</body>
</html>

templates/chat.html
<!DOCTYPE html>
<html lang="en">
<base href="/">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Page</title>
    <link rel="shortcut icon" type="x-icon" href="{{ url_for('static', filename="images/logo.png") }}">
    <link rel="stylesheet" href="{{ url_for('static', filename="css/chat.css") }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.3/jquery.mCustomScrollbar.min.css'>
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
</head>
<body class="dark">
    <nav class="sidebar">
        <header>
            <div class="image-text">
                <span class="image">
                    <img src="{{ url_for('static', filename="images/logo.png") }}" alt="">
                </span>

                <div class="text logo-text">
                    <span class="name">CODE GPT</span>
                    <span class="profession">Programming AI</span>
                </div>
            </div>

            <i class='bx bx-chevron-right toggle'></i>
        </header>

        <div class="menu-bar">
            <div class="menu">

                <ul class="menu-links">
                    <li class="nav-link">
                        <a href="{{ url_for("gpt.chat") }}">
                            <i class='bx bx-message-dots icon'></i>
                            <span class="text nav-text">Chat</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="{{ url_for("gpt.workspace") }}">
                            <i class='bx bx-code-alt icon'></i>
                            <span class="text nav-text">Workspace</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="{{ url_for("qa.blogs") }}">
                            <i class='bx bx-help-circle icon'></i>
                            <span class="text nav-text">Q&A</span>
                        </a>
                    </li>

                    {#  <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-user icon'></i>
                            <span class="text nav-text">Account</span>
                        </a>
                    </li>#}

                    <br>
                    <hr>


                    <!-- 历史记录 -->

                    <li class="nav-link">
                        <i class='bx bx-time-five icon'></i>
                        <span class="text nav-text">History</span>
                    </li>
                    <li class="search-box">
                        <i class='bx bx-search icon'></i>
                        <input type="text" placeholder="Search...">
                    </li>
                    <br>
                    {% for his in history %}
                        <ul id="history" class="text nav-text history">{{ his.content }}</ul>
                    {% endfor %}





                </ul>
            </div>

            <div class="bottom-content">
                <li class="">
                    <a href="{{ url_for("auth.logout") }}">
                        <i class='bx bx-log-out icon' ></i>
                        <span class="text nav-text">Log Out</span>
                    </a>
                </li>

                <li class="mode">
                    <div class="sun-moon">
                        <i class='bx bx-sun icon sun'></i>
                        <i class='bx bx-moon icon moon'></i>
                    </div>
                    <span class="mode-text text">Dark mode</span>

                    <div class="toggle-switch">
                        <span class="switch"></span>
                    </div>
                </li>

            </div>
        </div>

    </nav>

    <section class="home">
        <div class="chat">
            <div class="chat-title">
                <h1>CHat box</h1>
                <h2>AI</h2>
                <figure class="avatar">
                    <img src="{{ url_for('static', filename='images/C.jpg') }}" /></figure>
                <div class="dropdown-container">
                    <button class="dropdown-button main-button">
                        <span class="dropdown-title-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
                                <path d="M6 0L0 10h5l-2 6L16 6h-5L14 0z"/>
                            </svg>
                        </span>
                        <span class="dropdown-title text-truncate">Chat GPT3.5</span>
                        <span class="dropdown-arrow">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
                        <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
                        </svg>
                        </span>
                    </button>
                    <div class="dropdown-list-container">
                        <div class="dropdown-list-wrapper">
                        <ul class="dropdown-list"></ul>
                        <div class="floating-icon" aria-hidden="true"></div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="messages">
            <div class="messages-content"></div>
        </div>
        <div class="message-box">
            <textarea type="text" class="message-input" placeholder="Type message..."></textarea>
            <button type="submit" class="message-submit"><i class='bx bx-send' ></i></button>
        </div>

        </div>
        <div class="bg"></div>
        <!-- partial -->
        <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.3/jquery.mCustomScrollbar.concat.min.js'></script>
    <script src="{{ url_for('static', filename="js/chat.js") }}"></script>
    <script>
        const body = document.querySelector('body'),
              sidebar = body.querySelector('nav'),
              toggle = body.querySelector(".toggle"),
              searchBtn = body.querySelector(".search-box"),
              modeSwitch = body.querySelector(".toggle-switch"),
              modeText = body.querySelector(".mode-text");

        toggle.addEventListener("click", () => {
            sidebar.classList.toggle("close");
        });

        searchBtn.addEventListener("click", () => {
            sidebar.classList.remove("close");
        });

        modeSwitch.addEventListener("click", () => {
            body.classList.toggle("dark");
            if(body.classList.contains("dark")){
                modeText.innerText = "Dark mode";
            } else {
                modeText.innerText = "Light mode";
            }
        });
    </script>
    </section>
</body>
</html>

templates/intro.html
{% extends "navBar.html" %}

{% block title %}Intro{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/intro.css') }}">
{% endblock %}

{% block body %}
     <div class="video-container">
        <video src="{{ url_for('static', filename='images/handwrite.mov') }}" autoplay muted playsinline loop controlsList="nodownload" poster="video-poster.jpg"></video>
    </div>
    <!-- Content Section -->
    <div class="content">
        <h1>Welcome to Code GPT</h1>
        <p>Code GPT is an online resource dedicated to helping beginners overcome programming challenges. Whether you're a programming novice or have some experience as a developer, we offer the following services:</p>
        <ul>
            <li><strong>Programming Problem Solving:</strong> You can submit various programming questions to Code GPT, and our intelligent model will do its best to assist you in finding solutions.</li>
            <li><strong>Programming Guidance:</strong> We provide detailed guides on various programming languages, frameworks, and tools to help you better understand the world of programming.</li>
            <li><strong>Code Samples:</strong> We offer a vast collection of code examples and tutorials to help you learn and master programming skills.</li>
            <li><strong>Programming Resources:</strong> From coding standards to solutions for common errors, we provide a wide range of programming resources to help you become a better developer.</li>
        </ul>
        <p>Whether you're looking to start your journey into programming or delve deeper into programming knowledge, Code GPT is here to provide strong support. Start using our services and make your programming journey more enjoyable and accessible.</p>
    </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
</head>

<body>
    <header>
        <!-- Navigation Bar -->
        <nav class="top-menu">
        <ul>
            <li><a href="{{ url_for("gpt.chat") }}">CodeGPT</a></li>
            <li><a class="active" href="{{ url_for("index.intro") }}">Introduction</a></li>
            <li><a href="{{ url_for("auth.login") }}">Sign In/ up</a></li>
            <li><a href="{{ url_for("qa.blogs") }}">Q&A</a></li>
        </ul>
    </nav>
    </header>
    <div class="box">
        <div class="forms">
            <!-- Tips for switching between login and register forms -->
            <div class="tips">
                <span class="login-btn">Login</span>
                <span class="register-btn">Register</span>
            </div>
            <!-- Login Form -->
            <div class="login">
                <div class="form-title">
                    <h1>Hello</h1>
                    <h4>Code GPT</h4>
                </div>

                <form class="form" method="post">
                    <div class="username input-item">
                        <input type="text" name = "username" class="ipts" placeholder="">
                    </div>
                    <div class="password input-item">
                        <input type="password" name = "password" class="ipts" placeholder="">
                    </div>
                    <div class="other-select">
                        <!-- Remember password checkbox -->
                        <div class="rem-pwd">
                            <input type="checkbox" id="check">
                            <label for="check" class="rem-pwd-tips">Remember password</label>
                        </div>
                        <span class="fogot-pwd-btn">Forgot Password</span>
                    </div>
                    <button class="btn" type="submit">Login</button>
                </form>
            </div>
            <!-- Register Form -->
            <div class="register">
                <div class="form-title">
                    <h1>Register</h1>
                    <h4>Code GPT</h4>
                </div>
                <form class="form" method="POST">
                    <div class="username input-item">
                        <input type="text" name="username_register" class="ipts" placeholder="">
                    </div>
                    <div class="email input-item">
                        <input type="text" name="email" class="ipts" placeholder="">
                    </div>
                    <div class="code input-item">
                        <input type="text" name="captcha" class="ipts" placeholder="">
                        <span class="veri-code-tips">Click To Get</span>
                    </div>
                    <div class="password input-item">
                        <input type="password" name="password_register" class="ipts" placeholder="">
                    </div>
                    <div class="conform-password input-item">
                        <input type="password" name="password_confirm" class="ipts" placeholder=" ">
                    </div>
                    <button type="submit" class="btn">Register</button>
                </form>
            </div>
            <!-- Forgot Password Form -->
            <div class="fogot-pwd">
                <div class="form-title">
                    <h1>Forgot Password</h1>
                    <h4>Code GPT</h4>
                </div>
                <form class="form" method="POST">
                    <div class="username input-item">
                        <input type="text" name="username_forgot" class="ipts" placeholder="">
                    </div>
                    <div class="email input-item">
                        <input type="text" name="email_forgot" class="ipts" placeholder="">
                    </div>
                    <div class="password input-item">
                        <input type="password" name="password_forgot" class="ipts" placeholder="">
                    </div>
                    <div class="code input-item">
                        <input type="text" name="captcha_forgot" class="ipts" placeholder="">
                        <span class="veri-code-tips" id="veri-code-tips1">Click To Get</span>
                    </div>
                    <button type="submit" class="btn">Confirm</button>
                </form>
            </div>
        </div>
    </div>
</body>
<script>
    // Function to switch between pages (login, register, forgot password)
    function switchPage(showPage, hidePages) {
        showPage.style.opacity = '1';
        showPage.style.zIndex = '10';
        showPage.style.animation = 'into 1s ease';

        hidePages.forEach((page) => {
            page.style.opacity = '0';
            page.style.zIndex = '-1';
            page.style.animation = 'none';
        });
    }

    // Function to initialize countdown timer for verification code
    function initializeCountdownTimer(veriCodeTips) {
        let reckonTimeFlag = 5;
        let reckonTime;

        function countDown() {
            veriCodeTips.innerHTML = `RESEND (${reckonTimeFlag})`;
            reckonTimeFlag--;
            if (reckonTimeFlag < 0) {
                clearInterval(reckonTime);
                reckonTimeFlag = 5;
                veriCodeTips.innerHTML = `Click To Get`;
                veriCodeTips.style.color = "rgb(113, 123, 185)";
                veriCodeTips.onclick = veriCodeTipsClick;
            }
        }

        function veriCodeTipsClick() {
            veriCodeTips.onclick = null;
            veriCodeTips.style.color = "rgb(153, 151, 151)";
            reckonTime = setInterval(countDown, 1000);
            countDown();
        }

        veriCodeTips.addEventListener('click', function () {
            veriCodeTipsClick()
            var email = $("input[name='email']").val();
            $.ajax({
                url: "/auth/captcha/email?email=" + email,
                method: "GET",
                success: function (result) {
                    var code = result['code'];
                    if (code == 200) {
                        alert("Veri Code Sent！");
                    } else {
                        alert(result['message']);
                    }
                },
                fail: function (error) {
                    console.log(error);
                }
            })
        })
    }
    function initializeCountdownTimer1(veriCodeTips) {
        let reckonTimeFlag = 5;
        let reckonTime;

        function countDown() {
            veriCodeTips.innerHTML = `RESEND (${reckonTimeFlag})`;
            reckonTimeFlag--;
            if (reckonTimeFlag < 0) {
                clearInterval(reckonTime);
                reckonTimeFlag = 5;
                veriCodeTips.innerHTML = `Click To Get`;
                veriCodeTips.style.color = "rgb(113, 123, 185)";
                veriCodeTips.onclick = veriCodeTipsClick;
            }
        }

        function veriCodeTipsClick() {
            veriCodeTips.onclick = null;
            veriCodeTips.style.color = "rgb(153, 151, 151)";
            reckonTime = setInterval(countDown, 1000);
            countDown();
        }

        veriCodeTips.addEventListener('click', function () {
            veriCodeTipsClick()
            var email = $("input[name='email_forgot']").val();
            $.ajax({
                url: "/auth/captcha/email?email=" + email,
                method: "GET",
                success: function (result) {
                    var code = result['code'];
                    if (code == 200) {
                        alert("Veri Code Sent！");
                    } else {
                        alert(result['message']);
                    }
                },
                fail: function (error) {
                    console.log(error);
                }
            })
        })
    }

    // Get DOM elements
    const login = document.querySelector('.login');
    const register = document.querySelector('.register');
    const fogotPwd = document.querySelector('.fogot-pwd');
    const registerBtn = document.querySelector('.register-btn');
    const loginBtn = document.querySelector('.login-btn');
    const fogotPwdBtn = document.querySelector('.fogot-pwd-btn');
    const veriCodeTips = document.querySelector('.veri-code-tips');
    const veriCodeTips1 = document.getElementById('veri-code-tips1');

    // Initialize page
    initializeCountdownTimer(veriCodeTips);
    initializeCountdownTimer1(veriCodeTips1);

    // Add event listeners
    registerBtn.addEventListener('click', function () {
        switchPage(register, [login, fogotPwd]);
        registerBtn.style.borderBottom = '4px solid rgb(249, 177, 122)';
        registerBtn.style.color = '#fff';
        loginBtn.style.borderBottom = 'none';
        loginBtn.style.color = 'rgb(100, 108, 154)';
    });

    loginBtn.addEventListener('click', function () {
        switchPage(login, [register, fogotPwd]);
        loginBtn.style.borderBottom = '4px solid rgb(249, 177, 122)';
        loginBtn.style.color = '#fff';
        registerBtn.style.borderBottom = '';
        registerBtn.style.color = 'rgb(100, 108, 154)';
    });

    fogotPwdBtn.addEventListener('click', function () {
        switchPage(fogotPwd, [login, register]);
    });

</script>

</html>

templates/navBar.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
<header>
    <nav class="top-menu">
        <ul>
            <li><a href="{{ url_for("gpt.chat") }}">CodeGPT</a></li>
            <li><a class="active" href="{{ url_for("index.intro") }}">Introduction</a></li>
            {% if user %}
                <li><a href="{{ url_for("index.intro") }}">{{ user.username }}</a></li>
            {% else %}
                <li><a href="{{ url_for("auth.login") }}">Sign In/ up</a></li>
            {% endif %}
            <li><a href="{{ url_for("qa.blogs") }}">Q&A</a></li>
        </ul>
    </nav>
</header>


<div class="container">
    {% block body %}{% endblock %}
</div>
</body>
</html>